import type { EventCategory, Event } from "@/models/event";

const myEvents: Event[] = [
  {
    id: "1",
    name: "Fiesta de Año Nuevo",
    description: "Celebración con fuegos artificiales",
    image: "https://example.com/newyear.jpg",
    category: "Ocio",
    date: "Lunes, 31 dic",
    hour: "11:59 PM",
    location: "San José, Costa Rica",
    availableSpots: 50,
    status: "Activo",
  },
  {
    id: "2",
    name: "Conferencia Tech",
    description: "Evento sobre IA y blockchain",
    image: "https://example.com/tech.jpg",
    category: "Tecnología",
    date: "Viernes, 15 mar",
    hour: "09:00 AM",
    location: "Liberia, Guanacaste",
    availableSpots: 200,
    status: "Activo",


  },
  {
    id: "3",
    name: "Feria Gastronómica",
    description: "Exposición de comida local e internacional",
    image: "https://example.com/food.jpg",
    category: "Gastronomía",
    date: "Sábado, 10 abr",
    hour: "12:00 PM",
    location: "Alajuela, Costa Rica",
    availableSpots: 100,
    status: "Agotado",

  },
  {
    id: "4",
    name: "Maratón Solidario",
    description: "Corre por una causa",
    image: "https://example.com/marathon.jpg",
    category: "Deportes",
    date: "Domingo, 20 may",
    hour: "06:00 AM",
    location: "Heredia, Costa Rica",
    availableSpots: 500,
    status: "Proximamente",

  },
  {
    id: "5",
    name: "Exposición de Arte",
    description: "Obras de artistas locales",
    image: "https://example.com/art.jpg",
    category: "Cultura",
    date: "Miércoles, 2 jun",
    hour: "04:00 PM",
    location: "Cartago, Costa Rica",
    availableSpots: 30,
    status: "Proximamente",
  },
  {
    id: "6",
    name: "Torneo de Ajedrez",
    description: "Competencia para principiantes y expertos",
    image: "https://example.com/chess.jpg",
    category: "Juegos",
    date: "Sábado, 18 jul",
    hour: "10:00 AM",
    location: "Puntarenas, Costa Rica",
    availableSpots: 40,
    status: "Activo",
  },
  {
    id: "7",
    name: "Taller de Fotografía",
    description: "Aprende a capturar momentos únicos",
    image: "https://example.com/photo.jpg",
    category: "Educación",
    date: "Martes, 5 ago",
    hour: "03:00 PM",
    location: "Guanacaste, Costa Rica",
    availableSpots: 20,
    status: "Activo",
  },
  {
    id: "8",
    name: "Carrera de Drones",
    description: "Competencia de pilotos de drones",
    image: "https://example.com/drones.jpg",
    category: "Tecnología",
    date: "Domingo, 9 sep",
    hour: "02:00 PM",
    location: "San Carlos, Costa Rica",
    availableSpots: 60,
    status: "Agotado",
  },
  {
    id: "9",
    name: "Noche de Cine al Aire Libre",
    description: "Proyección de películas clásicas",
    image: "https://example.com/cinema.jpg",
    category: "Entretenimiento",
    date: "Viernes, 14 oct",
    hour: "07:00 PM",
    location: "San José, Costa Rica",
    availableSpots: 80,
    status: "Activo",
  },
  {
    id: "10",
    name: "Festival de Música",
    description: "Bandas nacionales e internacionales",
    image: "https://example.com/music.jpg",
    category: "Música",
    date: "Sábado, 22 nov",
    hour: "05:00 PM",
    location: "Cartago, Costa Rica",
    availableSpots: 300,
    status: "Agotado",
  },
  {
    id: "11",
    name: "Curso de Programación",
    description: "Aprende React Native desde cero",
    image: "https://example.com/coding.jpg",
    category: "Educación",
    date: "Lunes, 3 dic",
    hour: "06:00 PM",
    location: "Online",
    availableSpots: 100,
    status: "Activo",
  },
  {
    id: "12",
    name: "Exhibición de Autos Clásicos",
    description: "Vehículos icónicos de todos los tiempos",
    image: "https://example.com/cars.jpg",
    category: "Exhibición",
    date: "Domingo, 7 ene",
    hour: "09:00 AM",
    location: "Heredia, Costa Rica",
    availableSpots: 120,
    status: "Proximamente",
  },
  {
    id: "13",
    name: "Concierto de Rock",
    description: "Bandas locales e internacionales",
    image: "https://example.com/rock.jpg",
    category: "Música",
    date: "Viernes, 12 feb",
    hour: "08:00 PM",
    location: "San José, Costa Rica",
    availableSpots: 400,
    status: "Agotado",
  },
  {
    id: "14",
    name: "Curso de Idiomas",
    description: "Aprende inglés en 3 meses",
    image: "https://example.com/languages.jpg",
    category: "Educación",
    date: "Lunes, 8 mar",
    hour: "10:00 AM",
    location: "Online",
    availableSpots: 50,
    status: "Agotado",
  },
  {
    id: "15",
    name: "Competencia de Skate",
    description: "Demuestra tus mejores trucos",
    image: "https://example.com/skate.jpg",
    category: "Deportes",
    date: "Sábado, 24 abr",
    hour: "03:00 PM",
    location: "Alajuela, Costa Rica",
    availableSpots: 70,
    status: "Proximamente",
  },
  {
    id: "16",
    name: "Festival de Teatro",
    description: "Obras de dramaturgos nacionales",
    image: "https://example.com/theater.jpg",
    category: "Cultura",
    date: "Jueves, 10 may",
    hour: "07:00 PM",
    location: "Cartago, Costa Rica",
    availableSpots: 60,
    status: "Activo",
  },
  {
    id: "17",
    name: "Torneo de Videojuegos",
    description: "Compite en juegos de última generación",
    image: "https://example.com/gaming.jpg",
    category: "Juegos",
    date: "Domingo, 30 jun",
    hour: "01:00 PM",
    location: "San José, Costa Rica",
    availableSpots: 200,
    status: "Agotado",
  },
  {
    id: "18",
    name: "Día de la Bicicleta",
    description: "Recorrido en bicicleta por la ciudad",
    image: "https://example.com/bike.jpg",
    category: "Deportes",
    date: "Sábado, 20 jul",
    hour: "07:00 AM",
    location: "Puntarenas, Costa Rica",
    availableSpots: 150,
    status: "Proximamente",
  },
  {
    id: "19",
    name: "Taller de Escritura Creativa",
    description: "Aprende a escribir cuentos y novelas",
    image: "https://example.com/writing.jpg",
    category: "Educación",
    date: "Martes, 5 ago",
    hour: "05:00 PM",
    location: "Online",
    availableSpots: 30,
    status: "Activo",
  },
  {
    id: "20",
    name: "Festival de Jazz",
    description: "Músicos internacionales en vivo",
    image: "https://example.com/jazz.jpg",
    category: "Música",
    date: "Viernes, 15 sep",
    hour: "08:00 PM",
    location: "San José, Costa Rica",
    availableSpots: 250,
    status: "Agotado",
  },

  
];

export default myEvents;
